### ISSUE TITLE
RUNTASTIC GPS WATCH AND HEART RATE MONITOR

### ISSUE THREAD

**Issue by mpiana** [mru00/crane_gps_watch#13]
I just compiled on my Ubuntu 14.4 64 bit an downloaded a track from the Runtastic GPS Watch. 

https://www.runtastic.com/shop/en/runtastic-gps-watch-with-heart-rate-monitor

I confirrm that it works.

Thanks,
--- Max

**Comment by mru00** [comment]
Thanks, great.
could you please also post the firmware version?

**Comment by mpiana** [comment]
I don't know how to get it.

this are data on the back of the phone:
KRIPPL WATCHES WARENHANDLES GMBH
SERIAL NO: PO7049
ART. NO.: RUNGPS1-S
MODEL: D021280

**Comment by mpiana** [comment]
found it, with the verbose option :)
watch begin p=Running l=English version='Ver1.20' version2='.00.00.00.01.00.08.07.00.16' firmware='1.20.26_RUNT0_00' time

**Comment by mru00** [comment]
thanks!
