### ISSUE TITLE
install bug, autoreconf

### ISSUE THREAD

**Issue by mru00** [mru00/crane_gps_watch#14]
When i use ./confiugre to install the crane_gps_watch projekt, this line
appear

configure: error: cannot run /bin/bash ./config.sub

after a while, i figure out to install the paged autoreconf and run

autoreconf --install

after this i can install it :)

is this a bug of install your software ?

**Comment by renat-sabitov** [comment]
config.sub is a link .  config.guess and test-driver are also links. 
lrwxrwxrwx 1 srr srr 37 May 19 21:13 ./config.guess -> /usr/share/automake-1.14/config.guess
lrwxrwxrwx 1 srr srr 35 May 19 21:13 ./config.sub -> /usr/share/automake-1.14/config.sub
lrwxrwxrwx 1 srr srr 36 May 19 21:13 ./test-driver -> /usr/share/automake-1.14/test-driver
