### ISSUE TITLE
Program errors out after connecting to watch

### ISSUE THREAD

**Issue by AcouBass** [mru00/crane_gps_watch#16]
Full error:
```
Autodetecting serial ports
Opening serial port '/dev/ttyUSB0'
Connected to watch on '/dev/ttyUSB0'
error: Serial link: failed to read expected number of bytes expected: 1 actual: 0: Success
Terminating
```
I'm on Arch Linux, using the AUR PKGBUILD. I've added my user to the uucp group (After using ls -l on /dev/ttyUSB0 to see which groups have access to it) - There is apparently no dialout group to add myself to.  

I think this might be a PEBCAK issue, but I couldn't find any info online!  

I'm using a Crane GPS watch, though it's not a square one like the ones you linked - it looks more like this one from the Kripple site: https://www.krippl-watches.com/wp-content/uploads/2014/10/armbanduhren_gps_1.jpg

**Comment by knedlyk** [comment]
I had similar issue sever times, the problem was in bad contact between watch and serial cable. Clean 4 contacts in the watch, reconnect and try again.

**Comment by AcouBass** [comment]
Hmm. I've tried cleaning the contacts on both the watch and the little jawed cable end. I've also tried it on three different PC's - my main Arch 64-bit desktop, my 32-bit Arch laptop, and my dad's 32-bit Linux Mint PC (Using the dialout group instead of the uucp of Arch). Still getting this same error. Currently seeing if I can procure a Windows machine to test it using their official software to make sure my watch isn't borked!

**Comment by mru00** [comment]
Hi!

Do you know the device file (from dmesg for example)? Then you can use the "--device" command line option to bypass the auto detection. Perhaps that works better.


-- 
Rudolf Mühlbauer


-------- Original message --------

**Comment by mru00** [comment]
Do you have access to a windows machine? I think the original software shows the watch firmware version somewhere. This might give us a hint.


-- 
Rudolf Mühlbauer


-------- Original message --------

**Comment by AcouBass** [comment]
> Do you know the device file (from dmesg for example)? Then you can use the "--device" command line option to bypass the auto detection. Perhaps that works better.  

```
[18438.143513] cp210x 1-2.3:1.0: cp210x converter detected
[18438.144873] usb 1-2.3: cp210x converter now attached to ttyUSB0
```  

I've tried with --device /dev/ttyUSB0 and it gives the same results. I'm not sure, but I seem to actually connect to the ttyUSB0 device (as it says 'connected to watch).  

> Do you have access to a windows machine? I think the original software shows the watch firmware version somewhere. This might give us a hint.  

The best I can do right now is a VM, but I might be able to get hold of a Windows laptop tomorrow to test it on!

**Comment by AcouBass** [comment]
OK, I've just plugged the watch into a Windows laptop - The software picked  up the watch and I was able to view my rides (I have three stored in the watch, though only one is of any distance so actually shows up on the little map in the software).  

It says at the bottom that my watch is Ver: 1.20 - I tried updating the firmware through the software, but it wouldn't download it (kept erroring out, saying it couldn't download the firmware update). I'll try it again tomorrow - maybe all I need is that firmware update?

**Comment by mru00** [comment]
Good news... that means that your watch is basically working and not bricked.

To the version... there are several version strings reported. 
A) "Ver. 1.20". This is the same everywhere. Perhaps the hardware version or something.
B) "1.20.22_KRIP0_00". The firmware version.
C) some xx.xx.xx.xx.xx.xx string, no clue what that is (fw of gps?) , I just called it version 2 in my implementation. 

What is really interesting is B), the firmware version. Can you find that in the program?


-- 
Rudolf Mühlbauer


-------- Original message --------

**Comment by AcouBass** [comment]
OK, I've done a good scouring of the Windows program, and can't find anything at all about the firmware version besides the Watch: Ver 1.20 at the bottom. Even the updater doesn't tell me, as it just errors out before it gets anywhere!  

Is there any other way to find the version number besides the Windows software?

**Comment by mru00** [comment]
A usb snoop would help. I used the "serial port monitor" (linked in the readme), worked fine.

The log should also contain the port settings- perhaps just the baud rate is different. 


-- 
Rudolf Mühlbauer


-------- Original message --------

**Comment by AcouBass** [comment]
> A usb snoop would help. I used the "serial port monitor" (linked in the readme), worked fine. The log should also contain the port settings- perhaps just the baud rate is different.  

Alright, I couldn't get the one linked in your README.md working, but I dug up another one (Which is actually by HHD too, leading me to believe it's the same software, but whatever, it worked).  

Bear with me here, I'm not 100% sure what I'm supposed to be looking out for here, BUT I found a couple of lines in the dumped text file I created with the program (which I pasted here... warning it's a good 10k lines long) https://gist.github.com/anonymous/5d97ea48fd127317389a )  

```
00000060   00 00 00 01 00 31 2e 32 30 2e 30 33 5f 4b 52 49    .....1.20.03_KRI
00000070   50 30 5f 30 32 00 00 00 00 00 00 00 00 00 00 00    P0_02...........
```  

Does this mean the firmware is, in fact, 1.20.03 as opposed to the 1.20.22 you target?   

Also:  
```
0x00000005	4	unsigned long	  	CurrentBaudRate	115200	17.07.2015 00:49:51
```  

Is this the Baud Rate you were/weren't hoping for? There is also a line that says NewBaudRate, but the number doesn't change.

**Comment by mru00** [comment]
Perfect. This is exactly what I need. 
Baudrate is the same. That would have been too easy. 

You have the 1.20.03. It seems that they changed the protocol since then.
The easiest thing would be that you try to update the firmware to a more recent version. I don't have a clue how to do that if the "GPS master" software does not work.

I will have a look at the serial log. It could be something simple.




-- 
Rudolf Mühlbauer


-------- Original message --------

**Comment by mru00** [comment]
If I read the log correctly, your watch firmware does not implement the opcode I named "readVersion2".


Are you comfortable changing the code?

It's a wild guess: in the file "SerialLink.cpp", method "readVersion2", shortcut the method by inserting this before all the other code:

    return "unknown";

And comment out the rest of the method. 

This might overcome the connection problems. However, I can't tell if there are other changes too, so you might run in other problems.


-- 
Rudolf Mühlbauer


-------- Original message --------

**Comment by AcouBass** [comment]
This worked! :D  

Lines 74-84 of the file you mentioned now look like this:
```
std::string SerialLink::readVersion2() {
    return "unknown";
    std::vector<unsigned char> version;
    sendCommand(0x2c, std::vector<unsigned char>());
    receiveReply(0x2d, version);
    std::stringstream ss;
    for (auto v : version) {
        ss << "."  << std::setfill('0') << std::setw(2) <<  (int)v;
    }
    return ss.str();
}
```  

Software now syncs with the software and creates a .tcx of the ride it pulled (Yes, I ran around my house with the GPS on to make sure it had something recorded!).  

Unfortunately updating firmware seems to get me nowhere as the software just errors out when I try.

**Comment by mru00** [comment]
Great! I'm glad that it was so easy. 
I think I can changet that on the mainline; the "version2" was useless anyways.

**Comment by AcouBass** [comment]
Sounds good and thanks for making a fix! :D

**Comment by mru00** [comment]
Btw,
http://blog.lincomatic.com/?p=1707 shows how to update with some rebranded gps master software.
