### ISSUE TITLE
timezone off by 1

### ISSUE THREAD

**Issue by mru00** [mru00/crane_gps_watch#9]
Hi,

I noticed that the time being output for workouts were out by an hour.  I added some debugging to Watch:parseGpsTime:

void Watch::parseGpsTime(GpsTime& t, WatchMemoryBlock::mem_it_t it, unsigned timezone) {

    t.time.tm_year = 100 + *it++;

    t.time.tm_mon = *it++ - 1;

    t.time.tm_mday = *it++;

    t.time.tm_hour = *it++;

    t.time.tm_min = *it++;

    t.time.tm_sec = *it++;

    t.time.tm_gmtoff = ((timezone - 24)/2)*3600 + ((timezone - 24)%2)*1800;

    std::cout << t.time.tm_year << "/" << t.time.tm_mon << "/" << t.time.tm_mday << " " << t.time.tm_hour << ":" << t.time.tm_min << ":" << t.time.tm_sec << " " << t.time.tm_gmtoff << std::endl;

    t.mktime();

    std::cout << t.time.tm_year << "/" << t.time.tm_mon << "/" << t.time.tm_mday << " " << t.time.tm_hour << ":" << t.time.tm_min << ":" << t.time.tm_sec << " " << t.time.tm_gmtoff << std::endl;

}

For a given workout, I'll get output like this:

115/1/13 18:47:57 39600

115/1/13 19:47:57 39600

so it looks like t.mktime is shifting the time by an hour for some reason?  DST is in effect here, but the watch doesn't support that so it's timezone is set to GMT+11.

If I change line 69 of Datatypes.cpp to detect DST rather than assume it's off:

GpsTime::GpsTime() : time () {

    // explicit for documentation purposes:

    // see 'man mktime' for details.

    /*

       tm_isdst  A  flag  that  indicates  whether  daylight saving time is in$

                 effect at the time described.  The value is positive if  day‐$

                 light  saving time is in effect, zero if it is not, and nega‐$

                 tive if the information is not available.$

    */

    time.tm_isdst = -1;

}

I get correct outputs:

115/1/13 18:47:57 39600 -1

115/1/13 18:47:57 39600 1

I'm unsure if that will still be the case when DST is not in effect.

Cheers,

Andrew.

**Comment by Pierke** [comment]
Hi Andrew,

The only way I found to have the watch display the correct time when DST is in effect and have the watch synchronize it's time with the GPS time is by increasing the time zone by 1 when DST is in effect.

I found that I still have some runs from October in my watch these files show a +2:00 for the time zone.
Currently the time zone is what it's supposed to be +1:00.

If you did the same I guess you live in timezone +10.

If the time.tm_isdst = -1; change you propose displays always the same time as your watch and you use the same timezone + 1 trick when DST is in effect then this is a good fix and we should apply it.
In 2 weeks we can test it here as DST will be in effect here.

Regards,

Peter.

**Comment by mru00** [comment]
I need help on this. Before I try to implement any fixes, I need tests. If you can spare some time, please collect samples:

* bin files
* expected vs actual result
* your timezone

I need good coverage of all corner cases. I intend to use libfaketime to set up the regression

**Comment by Pierke** [comment]
Rudolf,

I have tested Andrews proposed change:

------------------------------------------------------------------------------------------------------------------------------------------
GpsTime::GpsTime() : time () {

    // explicit for documentation purposes:

    // see 'man mktime' for details.

    /*

       tm_isdst  A  flag  that  indicates  whether  daylight saving time is in$

                 effect at the time described.  The value is positive if  day‐$

                 light  saving time is in effect, zero if it is not, and nega‐$

                 tive if the information is not available.$

    */

    time.tm_isdst = -1;

}
------------------------------------------------------------------------------------------------------------------------------------------

before and after the summer time change here in the Netherlands.
I'm using it in my fork now for a couple of months and it works. 
RunKeeper reports correct start and end time in the winter and in the summer.
Only notable difference is in the file name during the winter it ends in +1:00.tcx and in the summer it ends in +2:00.tcx. This is expected, in the summer the timezone effectively shifts +1 becoming +2, so not a problem.

I propose to make this a pull_request and accept it.

Regards,

Peter.

**Comment by knedlyk** [comment]
In my case it doesn't work. I applied the proposed patch and didn't notice significant changes. Here a few details. My home time is UTC+3 (summer time, DST is in affect, normally it is UCT+2). I set the time zone in my watch as +3:00. But resulting tcx file contains "Lap StartTime="2015-08-15T14:40:05+02:00" and so on. Start time was 14:40, so that is correct, but shift +02:00 is incorrect.
Yarema

**Comment by Pierke** [comment]
Hi Yarema,

Sorry to hear it is not working for you.
With your watch configured at +3:00 I would expect to see a +03:00 in the "Lap StartTime" and also in the file-name(2015-08-15T14:40:05+03:00.tcx) if you use the --split option.
There can be several reasons why it not working on your system:
- the implementation of the c-library of your compiler or Linux distribution,
- the locale setting on your system .
- the time source: bios or network time.

I'm currently running Mint 17.2(64bit).
I have been running on a different system with Ubuntu 12.04(64bit)
My region is Europe, City Amsterdam, Network time enabled and 24h clock.

Hope this is somewhat helpful in getting it to work on your system.

regards,

Peter.

**Comment by knedlyk** [comment]
Damn, Pierke, you are right, local time on my computer set to UTC+2 for several reasons! I don't understand why local time on computer should affect the time set by the watch in the output file? It is not good, local computer time must not affect timezone taken from the watch. I imagine the following situation: I rode bike in States, then came to Europe and downloaded tracks on local  computer (with local time, of course) and obtained wrong start times. Let say in States it was 2 pm NY local time, after downloading track in Europe it will be 14:00+02:00, but it should be 14:00-04:00.
Best,
Yarema

**Comment by Pierke** [comment]
Hi Yarema,

something kept nagging so I started digging. After some testing I found that mktime() overrides the value in tm_isdst. Something Andrew also noted I think. After reading-up on the mktime() function of glib in found that mktime() ignores tm_gmtoff (the time-zone offset) and sets tm_gmtoff to the systems time-zone offset.
So I made a fix for this. Now the software uses the time-zone set in the watch.
I attached a screendump of the 'git diff' or you can have a look at the diff of my fork and the main branch.
Could you test the changes I made to see if it now is as you would expect?

Cheers,
Peter.

![screenshot from 2015-08-17 23 48 03](https://cloud.githubusercontent.com/assets/10872072/9318144/39290076-4541-11e5-9593-3a2a446c0853.png)

**Comment by knedlyk** [comment]
Hi Peter, great job! I have compiled your code and it works in my case, I've got +03:00 as it was set in my watch, in despite of local time zone on my computer was +2:00. 
@Rudolf, can you take a look on Peter's patch?
Best,
Yarema

**Comment by mru00** [comment]
Thank you guys for your effort! Indeed the patch looks promising. Too bad I still haven't written a testbench to verify it. But if you are confident with the fix I will merge it.
Can you create a pull request?

**Comment by ajfclark** [comment]
I'll test with my watch once DST comes back into effect down here...
